### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by vkhodygo** [Allen-Tildesley/examples#1]
Dear Dr. Allen

I get errors when I compile your source code. I tried to comment such lines in SConstruct to localize problematic source files. 

Here is the list of errors:
1.
```bash
$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build_md_nve_lj_omp build_smc_nvt_lj build_md_chain_nve_lj build_qmc_pi_sho build_grint build_test_pot_qq build_md_chain_mts_lj build_test_pot_gb build_md_nve_lj build_adjust build_test_pot_twist build_mc_npt_lj_ll build_mc_zvt_lj_ll build_bd_nvt_lj build_pair_distribution build_test_pot_at build_mc_chain_wl_sw build_test_pot_dq build_md_nve_hs build_mc_chain_nvt_sw build_md_nvt_lj build_mc_nvt_lj_re build_mc_nvt_poly_lj build_md_nvt_lj_llle build_md_nve_lj_ll build_test_pot_bend build_md_nvt_lj_le build_test_pot_dd build_cluster build_mc_zvt_lj build_error_calc build_mc_nvt_lj_ll build_initialize build_eos_hs build_diffusion build_mc_nvt_sc build_t_tensor build_mc_npt_hs build_mc_npt_lj build_mc_nvt_lj build_mc_nvt_hs build_eos_lj build_hit_and_miss build_qmc_walk_sho build_sample_mean build_mc_npt_sc build_md_nve_lj_vl build_md_lj_mts build_mc_chain_nvt_cbmc_lj build_md_npt_lj build_dpd build_mc_gibbs_lj build_corfun build_mesh build_fft3dwrap build_wl_hist build_qmc_pi_lj build_diffusion_test
gfortran -o build_diffusion_test/diffusion_test.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_diffusion_test -Jbuild_diffusion_test build_diffusion_test/diffusion_test.f90
build_diffusion_test/diffusion_test.f90:134:73:

     CALL random_normals ( 0.0, SQRT(temperature), zeta ) ! Random momenta
                                                                         1
Error: There is no specific subroutine for the generic ‘random_normals’ at (1)
build_diffusion_test/diffusion_test.f90:84:51:

   CALL random_normals ( 0.0, SQRT(temperature), v )
                                                   1
Error: There is no specific subroutine for the generic ‘random_normals’ at (1)
scons: *** [build_diffusion_test/diffusion_test.o] Error 1
scons: building terminated because of errors. 
```
2)
```bash
$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build_md_nve_lj_omp build_smc_nvt_lj build_md_chain_nve_lj build_qmc_pi_sho build_grint build_test_pot_qq build_md_chain_mts_lj build_test_pot_gb build_md_nve_lj build_adjust build_test_pot_twist build_mc_npt_lj_ll build_mc_zvt_lj_ll build_bd_nvt_lj build_pair_distribution build_test_pot_at build_mc_chain_wl_sw build_test_pot_dq build_md_nve_hs build_mc_chain_nvt_sw build_md_nvt_lj build_mc_nvt_lj_re build_mc_nvt_poly_lj build_md_nvt_lj_llle build_md_nve_lj_ll build_test_pot_bend build_md_nvt_lj_le build_test_pot_dd build_cluster build_mc_zvt_lj build_error_calc build_mc_nvt_lj_ll build_initialize build_eos_hs build_diffusion build_mc_nvt_sc build_t_tensor build_mc_npt_hs build_mc_npt_lj build_mc_nvt_lj build_mc_nvt_hs build_eos_lj build_hit_and_miss build_qmc_walk_sho build_sample_mean build_mc_npt_sc build_md_nve_lj_vl build_md_lj_mts build_mc_chain_nvt_cbmc_lj build_md_npt_lj build_dpd build_mc_gibbs_lj build_corfun build_mesh build_fft3dwrap build_wl_hist build_qmc_pi_lj
gfortran -o build_qmc_pi_lj/qmc_pi_lj.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_qmc_pi_lj -Jbuild_qmc_pi_lj build_qmc_pi_lj/qmc_pi_lj.f90
build_qmc_pi_lj/qmc_pi_lj.f90:151:49:

               rik(:) = random_translate_vector ( dr_max/box, r(:,i,k) ) ! Trial move to new position (in box=1 units) 
                                                 1
Error: Type mismatch in argument ‘dr_max’ at (1); passed REAL(8) to REAL(4)
build_qmc_pi_lj/qmc_pi_lj.f90:164:35:

                  IF ( metropolis ( delta ) ) THEN ! Accept Metropolis test
                                   1
Error: Type mismatch in argument ‘delta’ at (1); passed REAL(8) to REAL(4)
scons: *** [build_qmc_pi_lj/qmc_pi_lj.o] Error 1
scons: building terminated because of errors.
```
3)
```bash
$ scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build_md_nve_lj_omp build_smc_nvt_lj build_md_chain_nve_lj build_qmc_pi_sho build_grint build_test_pot_qq build_md_chain_mts_lj build_test_pot_gb build_md_nve_lj build_adjust build_test_pot_twist build_mc_npt_lj_ll build_mc_zvt_lj_ll build_bd_nvt_lj build_pair_distribution build_test_pot_at build_mc_chain_wl_sw build_test_pot_dq build_md_nve_hs build_mc_chain_nvt_sw build_md_nvt_lj build_mc_nvt_lj_re build_mc_nvt_poly_lj build_md_nvt_lj_llle build_md_nve_lj_ll build_test_pot_bend build_md_nvt_lj_le build_test_pot_dd build_cluster build_mc_zvt_lj build_error_calc build_mc_nvt_lj_ll build_initialize build_eos_hs build_diffusion build_mc_nvt_sc build_t_tensor build_mc_npt_hs build_mc_npt_lj build_mc_nvt_lj build_mc_nvt_hs build_eos_lj build_hit_and_miss build_qmc_walk_sho build_sample_mean build_mc_npt_sc build_md_nve_lj_vl build_md_lj_mts build_mc_chain_nvt_cbmc_lj build_md_npt_lj build_dpd build_mc_gibbs_lj build_corfun build_mesh build_fft3dwrap build_wl_hist
gfortran -o build_wl_hist/wl_hist.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_wl_hist -Jbuild_wl_hist build_wl_hist/wl_hist.f90
gfortran -o build_wl_hist/wl_hist build_wl_hist/wl_hist.o
gfortran -o build_fft3dwrap/fft3dwrap.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -I/opt/local/include -Ibuild_fft3dwrap -Jbuild_fft3dwrap build_fft3dwrap/fft3dwrap.f90
f951: Warning: Nonexistent include directory ‘/opt/local/include’ [-Wmissing-include-dirs]
build_fft3dwrap/fft3dwrap.f90:9: Error: Can't open included file 'fftw3.f03'
scons: *** [build_fft3dwrap/fft3dwrap.o] Error 1
scons: building terminated because of errors.

```
The last one is  quite trivial, however, some people use math libraries from repositories. I think, it's possible to include such condition in the file.

P.S. This is fascinating that your new book is coming.

**Comment by Allen-Tildesley** [comment]
Thanks for your interest. The programs are not ready yet, and we won't be publicizing them until the book is published. Nonetheless, I believe that the Fortran codes should be nearly complete.

Everything "works for me": no compilation or build issues.

On Issues 1 and 2, your implementation of scons seems not to be compiling the required modules before tacklng the main program. When I run scons I get, for diffusion_test:

scons: building associated VariantDir targets: build_md_nve_lj_omp build_smc_nvt_lj build_md_chain_nve_lj build_qmc_pi_sho build_grint build_test_pot_qq build_md_chain_mts_lj build_test_pot_gb build_md_nve_lj build_adjust build_test_pot_twist build_mc_npt_lj_ll build_mc_zvt_lj_ll build_bd_nvt_lj build_pair_distribution build_test_pot_at build_mc_chain_wl_sw build_test_pot_dq build_md_nve_hs build_mc_chain_nvt_sw build_md_nvt_lj build_mc_nvt_lj_re build_mc_nvt_poly_lj build_md_nvt_lj_llle build_md_nve_lj_ll build_test_pot_bend build_md_nvt_lj_le build_test_pot_dd build_cluster build_mc_zvt_lj build_error_calc build_mc_nvt_lj_ll build_initialize build_eos_hs build_diffusion build_mc_nvt_sc build_t_tensor build_mc_npt_hs build_mc_npt_lj build_mc_nvt_lj build_mc_nvt_hs build_eos_lj build_hit_and_miss build_qmc_walk_sho build_sample_mean build_mc_npt_sc build_md_nve_lj_vl build_md_lj_mts build_mc_chain_nvt_cbmc_lj build_md_npt_lj build_dpd build_mc_gibbs_lj build_corfun build_mesh build_fft3dwrap build_wl_hist build_qmc_pi_lj build_diffusion_test
gfortran -o build_diffusion_test/config_io_module.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_diffusion_test -Jbuild_diffusion_test build_diffusion_test/config_io_module.f90
gfortran -o build_diffusion_test/maths_module.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_diffusion_test -Jbuild_diffusion_test build_diffusion_test/maths_module.f90
gfortran -o build_diffusion_test/diffusion_test.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_diffusion_test -Jbuild_diffusion_test build_diffusion_test/diffusion_test.f90
gfortran -o build_diffusion_test/diffusion_test build_diffusion_test/diffusion_test.o build_diffusion_test/config_io_module.o build_diffusion_test/maths_module.o

followed by, for qmc_pi_lj

gfortran -o build_qmc_pi_lj/averages_module.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_qmc_pi_lj -Jbuild_qmc_pi_lj build_qmc_pi_lj/averages_module.f90
gfortran -o build_qmc_pi_lj/config_io_module.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_qmc_pi_lj -Jbuild_qmc_pi_lj build_qmc_pi_lj/config_io_module.f90
gfortran -o build_qmc_pi_lj/lrc_lj_module.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_qmc_pi_lj -Jbuild_qmc_pi_lj build_qmc_pi_lj/lrc_lj_module.f90
gfortran -o build_qmc_pi_lj/maths_module.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_qmc_pi_lj -Jbuild_qmc_pi_lj build_qmc_pi_lj/maths_module.f90
gfortran -o build_qmc_pi_lj/qmc_pi_lj_module.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_qmc_pi_lj -Jbuild_qmc_pi_lj build_qmc_pi_lj/qmc_pi_lj_module.f90
gfortran -o build_qmc_pi_lj/qmc_pi_lj.o -c -fdefault-real-8 -fall-intrinsics -std=f2008 -Wall -Ibuild_qmc_pi_lj -Jbuild_qmc_pi_lj build_qmc_pi_lj/qmc_pi_lj.f90
gfortran -o build_qmc_pi_lj/qmc_pi_lj build_qmc_pi_lj/qmc_pi_lj.o build_qmc_pi_lj/qmc_pi_lj_module.o build_qmc_pi_lj/lrc_lj_module.o build_qmc_pi_lj/config_io_module.o build_qmc_pi_lj/averages_module.o build_qmc_pi_lj/maths_module.o

In your compilation I only see attempts to compile the main program. So my advice is to look into your scons installation and see if you can determine why this is happening. Any Fortran build would need to identify and handle the module files first.

On Issue 3, our aim is to wrap an FFT routine from the FFTW library. We are not trying to provide a general-purpose program that would attempt to choose between several libraries. So, it is necessary to install FFTW first and, if necessary, modify the variable that points to it, before compilation.

**Comment by Allen-Tildesley** [comment]
I'm closing this issue now, as the compilation works for me, and the fault seems to lie in your version of scons. I have added a note to the README warning readers that their scons installation needs to be up to date (if they intend to use scons), that other ways of building the programs are available, and also that we cannot give additional support to the build process on the variety of machines out there.
