### ISSUE TITLE
bug in md_nve_hs.f90 on lines 158-165

### ISSUE THREAD

**Issue by ericsmoll** [Allen-Tildesley/examples#10]
Is there a bug in md_nve_hs.f90 on lines 158-165? I understand that this strategy stores a collision partner in the partner array using the lower of the two collision indices. However, the collision between i and j can open up collisions of partner(k) with any other hard sphere, correct? This should require calling update with 'gt' and 'lt' in the loop making it unnecessary to call update ( i, box, lt ) and update ( j, box, lt ) outside the loop.

`           ! Update collision lists
           DO k = 1, n
              IF ( k==i .OR. k==j .OR. partner(k) == i .OR.  partner(k) == j ) THEN
                 CALL update ( k, box, gt ) ! Search for partners >k
              END IF
           END DO
           CALL update ( i, box, lt ) ! Search for partners <i
CALL update ( j, box, lt ) ! Search for partners <j`

**Comment by Michael-P-Allen** [comment]
Hi there, thanks for your interest. No, I don't think that this is a bug. In the loop, only the cases k==i and k==j correspond to the spheres whose trajectories have actually been changed by the collision. Therefore they need checking against all possible other collision partners: by calling update with "gt" (in the loop) and also explicitly with "lt" after the loop. In either case, as you have noted, any upcoming collision is stored under the lower index. The other spheres k, not equal to i or j, who were originally flagged as possible partners of either i or j, only need checking with "gt" (as was done when the collision lists were originally constructed; it is a standard "distinct pairs" calculation). An upcoming collision of k with another sphere m, where m<k, will already have been considered, and stored if necessary, under index m. Only those cases where m>k can have been overwritten by the projected collision with i or j, which will now never happen: these are the cases that need re-examining. I accept that this is a subtle point. But I don't believe that it is a bug. Let me know if you agree, or if you are still not convinced.

**Comment by ericsmoll** [comment]
> An upcoming collision of k with another sphere m, where m<k, will already have been considered, and stored if necessary, under index m. Only those cases where m>k can have been overwritten by the projected collision with i or j, which will now never happen: these are the cases that need re-examining

How clever. I agree with you. Thank you for the clear explanation. This is not a bug.
