### ISSUE TITLE
Long Range Corrections for Forces

### ISSUE THREAD

**Issue by ommair** [Allen-Tildesley/examples#13]
Hi Allen,
It is more conceptual question. In MD we add lrc beyond cutoff radius for configurational energy why dont we consider or add any thing for forces coming from lj like interactions beyond cutoff radius? I can understand taking derivative of lj potential energy would increase one extra power in denominator for each term which will decrease the forces between particles with increasing separation. Please explain or give me some reference for this.

**Comment by Michael-P-Allen** [comment]
Thanks for your question. Actually, we intend to keep these issues purely for flagging, and fixing, errors in the codes or accompanying guides. Unfortunately we didn't make this sufficiently clear - my fault. Shortly, I will add a CONTRIBUTING.md file to the repository which will clarify this, for the future. If you wish to send me your question by email, m.p.allen@bristol.ac.uk, I'll be happy to respond (although I can't promise to answer every question on molecular simulation!). Meanwhile I'll close this issue with the "invalid" tag (don't be offended, it is simply a tag).
